#!/usr/bin/env bash

set -e

# Load functions
source "./operations/arithmetic"
source "./operations/file_and_dir"
source "./operations/comparison"
source "./operations/string"
source "./operations/other"

function map {
  local fn_arg="$1"
  shift
  local args="$*"

  if [ "$(declare -f "$fn_arg" > /dev/null; echo $?)" -gt 0 ]; then
    echo "$fn_arg" is not a valid function for map
    exit 1
  fi

  # Change IFS to preserve whitespace in filenames
  local old_ifs=$IFS
  IFS=''

  while read -r line; do
    eval "$fn_arg" "'$line'" "'$args'"
  done < /dev/stdin

  IFS=$old_ifs
}

export -f map
