jobs:
  include:
  - language: bash
    addons:
      apt:
        packages:
          - parallel  # Used for bats
    script: make ci-bash
  - language: python
    python: 3.7
    script: make ci-py
