#!/usr/bin/env bash

set -e

function _map {
  local fn_arg="$1"
  shift
  local args="$*"

  if [ "$(declare -f "$fn_arg" > /dev/null; echo $?)" -gt 0 ]; then
    printf "%s %s\n" "$fn_arg" "is not a valid function for map" >&2
    exit 1
  fi

  # If empty input exit with 1
  if test -t 0; then
    exit 1
  fi

  # Change IFS to preserve whitespace in filenames
  local old_ifs=$IFS
  IFS=''

  while read -r line; do
    eval "$fn_arg" "'$line'" "'$args'"
  done < /dev/stdin

  IFS=$old_ifs
}

export -f _map
